version: 2.1
orbs:
  cloudfoundry: circleci/cloudfoundry@dev:eddie

workflows:
  build_deploy:
    jobs:
      - cloudfoundry/push:
          context: Demos-Context
          appname: build_bully
          org: eddies-org
          space: circleci
          manifest: manifest.yaml
          package: .
